### ISSUE TITLE
Compatibility with Active Admin 2

### ISSUE THREAD

**Issue by filipewl** [blocknotes/activeadmin_active_resource#3]
Hey!

I tried using this gem with an Active Admin (AA) `2.3.1` (as of now the most recent version is [`2.6.0`](https://github.com/activeadmin/activeadmin/blob/9da88933d40ec29eaef3091054ef71ecb760c15f/lib/active_admin/version.rb#L2)) app and got this warning about the gem depending on AA `~> 1.0`:

```
> bundle install

Fetching gem metadata from https://rubygems.org/.
Resolving dependencies.....
Bundler could not find compatible versions for gem "activeadmin":
  In snapshot (Gemfile.lock):
    activeadmin (= 2.3.1)

  In Gemfile:
    activeadmin

    activeadmin_active_resource was resolved to 0.1.3, which depends on
      activeadmin (~> 1.0)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

I relaxed the version to `~> 2.0` (1) in my local gem setup and it worked.

(1): https://github.com/blocknotes/activeadmin_active_resource/blob/e7e463867a413b6083ecea4a8aef69628b4466a7/activeadmin_active_resource.gemspec#L18

Is it okay to bump it?

**Comment by blocknotes** [comment]
Hey @filipewl. 
Sorry for replying so late.
Added supports ActiveAdmin 2.X finally.
